$$ \text{cov}(X, Y) = \sum_{i=1}^{n} p_i(x_i - \mu)(y_i - \nu)     $$
$$ p_i也就是f(x_i,y_i)这两个变量出现的概率                             $$     
$$ {\displaystyle \operatorname {E} (X)=\int _{\Omega }X\,dP=\mu }  $$
$$ {\displaystyle \operatorname {E} (Y)=\int _{\Omega }Y\,dP=\nu } $$

这里用到了XY的加权平均(期望)

# REF: https://www.zhihu.com/question/26235175
协方差是用于衡量两个随机变量之间关系的统计量.
协方差是两个统计量的取舍偏离样本的程序的乘积再对概率与加权平均值.

协方差衡量了两个变量的变化趋势是否一致。
- 如果两个变量的变化趋势相似，协方差为正；
- 如果一个变量增大时另一个变量减小，协方差为负；
- 如果两者独立，协方差为零。

相关英语:
- 协方差: covariance
- 相关系数: correlation coefficient

In [2]:
import numpy as np

# 生成两个示例变量
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# 计算协方差矩阵
cov_matrix = np.cov(x, y)

# 打印协方差矩阵
print(cov_matrix)

[[ 2.5 -2.5]
 [-2.5  2.5]]


In [3]:
x = np.arange(10)
y = 2 * x + np.random.uniform(0, 0.1, size=10)
cov_matrix = np.cov(x, y)
print(cov_matrix)
'''
cov(x, x) cov(x, y)
cov(y, x) cov(y, y) <- 这个更容易偏离期望 方差很大 波动性大 
'''

[[ 9.16666667 18.33681063]
 [18.33681063 36.6812701 ]]


$$ \text{cor}(X, Y) = \frac{\text{cov}(X, Y)}{\sigma_X \cdot \sigma_Y} $$

其中$\sigma$是各自的标准差, 期望/标准差本质就是标准化的步骤

conclude: 相关系数是协方差的标准化

协方差矩阵如下 反映各个随机变量之间的协方差 ![](./assets/cov-matrix.png)

In [5]:
# 相关系数矩阵
cc = np.corrcoef(x, y)
cc

array([[1.        , 0.99999055],
       [0.99999055, 1.        ]])